packages:
  - packages/*
ignoredBuiltDependencies:
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - faiss-node
  - protobufjs
  - vue-demi
  - sharp
  - '@xenova/transformers'
