packages:
  - packages/*
ignoredBuiltDependencies:

# 特殊的包处理  pnpm rebuild better-sqlite3
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - faiss-node
  - protobufjs
  - sharp
  - vue-demi
